[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[[services]]
name = "fitsync-backend"
source = "."

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[services.variables]
PORT = { default = "8000" }
NODE_ENV = { default = "production" }