services:
  - type: web
    name: fitsync-ai-backend
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false

databases:
  - name: fitsync-ai-db
    plan: free
    databaseName: fitsync_ai
    user: fitsync_user